version: '3'
services:
    jenkins:
        build:
            context: .
            dockerfile: Dockerfile_jenkins
        ports:
            - '80:8080'
            - '443:8443'
            - '50000:50000'

    test-jon-app-01:
        container_name: test-JON-app-01
        build:
            context: .
            dockerfile: Dockerfile_servers
    test-jon-app-02:
        container_name: test-JON-app-02
        build:
            context: .
            dockerfile: Dockerfile_servers
    prod-jon-app-01:
        container_name: prod-JON-app-01
        build:
            context: .
            dockerfile: Dockerfile_servers
    prod-jon-app-02:
        container_name: prod-JON-app-02
        build:
            context: .
            dockerfile: Dockerfile_servers
