---
- hosts: "all"
  tasks:
    - name: Include package list
      include_vars: server-patching-servers.prod.yml

    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 1

    - name: Upgrade package sources
      become: yes
      apt:
        pkg: "{{ item.name }}={{ item.version }}"
      with_items: "{{ Packages }}"
      when: "{{ Packages != None }}"
