---
- hosts: "all"
  tasks:
    - name: Update apt cache
      become: yes
      apt:
          update_cache: yes
          cache_valid_time: 1

    - name: Upgrade package sources
          become: yes
          apt:
            upgrade: yes
            name:

    - name: Write out report
      local_action: { module: "copy", content: "{{ package_updates_available.stdout }}", dest: "./server-patching-{{ group_names.0 }}.txt" }
      check_mode: no
