---
- hosts: "{{ target_environment }}_{{ region }}"
  tasks:
    - name: Include package list
      include_vars:
        file: "server-patching-{{ inventory_hostname }}.yml"

    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 1

    - name: Upgrade package sources
      become: yes
      apt:
        pkg: "{{ item.name }}={{ item.version }}"
      with_items: "{{ Packages }}"
      when: "{{ Packages != None }}"
